/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import java.text.DecimalFormat;

/**
 *
 * @author jdoni
 */
public class TelaCalc extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalc
     */
    public TelaCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spinnerPercentualFarinha = new javax.swing.JSpinner();
        spinnerPercentualLevain = new javax.swing.JSpinner();
        spinnerPercentualAgua = new javax.swing.JSpinner();
        spinnerPercentualAzeite = new javax.swing.JSpinner();
        spinnerPercentualSal = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        spinnerPesoLevain = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        lblPesoFarinha = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblAzeite = new javax.swing.JLabel();
        lblSal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora do Pão");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Farinha");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 30, 67, -1));

        jLabel2.setText("Levain");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 67, -1));

        jLabel3.setText("Água");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 67, -1));

        jLabel4.setText("Azeite");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 120, 67, -1));

        jLabel5.setText("Sal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 150, 67, -1));

        spinnerPercentualFarinha.setModel(new javax.swing.SpinnerNumberModel(100, 0, 100, 1));
        spinnerPercentualFarinha.setEnabled(false);
        getContentPane().add(spinnerPercentualFarinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        spinnerPercentualLevain.setModel(new javax.swing.SpinnerNumberModel(30, 0, 100, 1));
        spinnerPercentualLevain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPercentualLevainStateChanged(evt);
            }
        });
        getContentPane().add(spinnerPercentualLevain, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        spinnerPercentualAgua.setModel(new javax.swing.SpinnerNumberModel(65, 0, 100, 1));
        spinnerPercentualAgua.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPercentualAguaStateChanged(evt);
            }
        });
        getContentPane().add(spinnerPercentualAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        spinnerPercentualAzeite.setModel(new javax.swing.SpinnerNumberModel(4, 0, 100, 1));
        spinnerPercentualAzeite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPercentualAzeiteStateChanged(evt);
            }
        });
        getContentPane().add(spinnerPercentualAzeite, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        spinnerPercentualSal.setModel(new javax.swing.SpinnerNumberModel(2, 0, 100, 1));
        spinnerPercentualSal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPercentualSalStateChanged(evt);
            }
        });
        getContentPane().add(spinnerPercentualSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pao2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 200, 200));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Peso grs");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 6, 80, -1));

        spinnerPesoLevain.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        spinnerPesoLevain.setModel(new javax.swing.SpinnerNumberModel(110, null, null, 1));
        spinnerPesoLevain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPesoLevainStateChanged(evt);
            }
        });
        getContentPane().add(spinnerPesoLevain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("%");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 6, 69, -1));

        lblPesoFarinha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesoFarinha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPesoFarinha.setText("0");
        getContentPane().add(lblPesoFarinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 80, -1));

        lblAgua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAgua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAgua.setText("0");
        getContentPane().add(lblAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 80, 20));

        lblAzeite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAzeite.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAzeite.setText("0");
        getContentPane().add(lblAzeite, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 80, -1));

        lblSal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSal.setText("0");
        getContentPane().add(lblSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Peso Total ");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, -1));

        lblPesoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesoTotal.setForeground(new java.awt.Color(0, 0, 204));
        lblPesoTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPesoTotal.setText("0");
        lblPesoTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblPesoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 80, -1));

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        getContentPane().add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinnerPesoLevainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPesoLevainStateChanged
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_spinnerPesoLevainStateChanged

    private void spinnerPercentualLevainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPercentualLevainStateChanged
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_spinnerPercentualLevainStateChanged

    private void spinnerPercentualAguaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPercentualAguaStateChanged
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_spinnerPercentualAguaStateChanged

    private void spinnerPercentualAzeiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPercentualAzeiteStateChanged
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_spinnerPercentualAzeiteStateChanged

    private void spinnerPercentualSalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPercentualSalStateChanged
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_spinnerPercentualSalStateChanged

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_formWindowActivated

    private void calcula(){
        
        percentualLevain = Integer.parseInt(spinnerPercentualLevain.getValue().toString());
        pesoLevain = Integer.parseInt(spinnerPesoLevain.getValue().toString());
        percentualAgua = Integer.parseInt(spinnerPercentualAgua.getValue().toString());
        percentualAzeite = Integer.parseInt(spinnerPercentualAzeite.getValue().toString());
        percentualSal = Integer.parseInt(spinnerPercentualSal.getValue().toString());

        System.out.println(percentualLevain);
        System.out.println(pesoLevain);
        System.out.println(pesoLevain / (percentualLevain / 100));
        
        pesoFarinha = pesoLevain / (percentualLevain / 100);
                
        pesoAgua = pesoFarinha * (percentualAgua / 100);
        pesoAzeite = pesoFarinha * (percentualAzeite / 100);
        pesoSal = pesoFarinha * (percentualSal / 100);
        
        pesoTotal = pesoFarinha + pesoLevain + pesoAgua + pesoAzeite + pesoSal;
        
        lblPesoFarinha.setText(df.format(pesoFarinha));
        lblAgua.setText(df.format(pesoAgua));
        lblAzeite.setText(df.format(pesoAzeite));
        lblSal.setText(df.format(pesoSal));
        lblPesoTotal.setText(df.format(pesoTotal));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblAzeite;
    private javax.swing.JLabel lblPesoFarinha;
    private javax.swing.JLabel lblPesoTotal;
    private javax.swing.JLabel lblSal;
    private javax.swing.JSpinner spinnerPercentualAgua;
    private javax.swing.JSpinner spinnerPercentualAzeite;
    private javax.swing.JSpinner spinnerPercentualFarinha;
    private javax.swing.JSpinner spinnerPercentualLevain;
    private javax.swing.JSpinner spinnerPercentualSal;
    private javax.swing.JSpinner spinnerPesoLevain;
    // End of variables declaration//GEN-END:variables
    private double pesoFarinha;
    private double percentualLevain;
    private double pesoLevain;
    private double percentualAgua;
    private double pesoAgua;
    private double percentualAzeite;
    private double pesoAzeite;
    private double percentualSal;
    private double pesoSal;
    private double pesoTotal;
    DecimalFormat df = new DecimalFormat("###,###"); 
}
